/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type QuoteRequest = {
  _id: string;
  _type: "quoteRequest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: "new" | "contacted" | "closed" | "spam";
  name?: string;
  method?: "email" | "whatsapp" | "telegram";
  contact?: string;
  receivedAt?: string;
  emailSent?: boolean;
  notes?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Case = {
  _id: string;
  _type: "case";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  client?: string;
  category?: "commercial" | "youtube" | "short";
  year?: number;
  scope?: Array<string>;
  summary?: string;
  order?: number;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  fullVideoFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  fullVideoUrl?: string;
  previewVideoFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  previewVideoUrl?: string;
  orientation?: "horizontal" | "vertical";
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  brief?: string;
  idea?: string;
  result?: string;
  credits?: Array<{
    role?: string;
    name?: string;
    _type: "credit";
    _key: string;
  }>;
  testimonial?: {
    quote?: string;
    author?: string;
    role?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  legalName?: string;
  registeredName?: string;
  location?: string;
  email?: string;
  phone?: string;
  telegram?: string;
  instagram?: string;
  linkedin?: string;
};

export type CaseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "case";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    title?: string;
    subtitle?: string;
    ctaLabel?: string;
    showreelFile?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    showreelUrl?: string;
    poster?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  about?: {
    heading?: string;
    lead?: string;
    body?: string;
    stats?: Array<{
      value?: string;
      label?: string;
      _type: "stat";
      _key: string;
    }>;
    clients?: Array<{
      name?: string;
      logo?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      _type: "client";
      _key: string;
    }>;
  };
  portfolio?: {
    title?: string;
    intro?: string;
    cases?: Array<
      {
        _key: string;
      } & CaseReference
    >;
  };
  faq?: {
    title?: string;
    intro?: string;
    items?: Array<{
      question?: string;
      answer?: string;
      _type: "faqItem";
      _key: string;
    }>;
  };
  contact?: {
    title?: string;
    lede?: string;
  };
  seo?: {
    title?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | QuoteRequest
  | SanityImageAssetReference
  | SanityFileAssetReference
  | Case
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SiteSettings
  | CaseReference
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_id == "siteSettings" && _type == "siteSettings"][0] {    name,    legalName,    registeredName,    location,    email,    phone,    telegram,    instagram,    linkedin  }
export type SETTINGS_QUERY_RESULT = {
  name: string | null;
  legalName: string | null;
  registeredName: string | null;
  location: string | null;
  email: string | null;
  phone: string | null;
  telegram: string | null;
  instagram: string | null;
  linkedin: string | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: HOME_QUERY
// Query: *[_id == "homePage" && _type == "homePage"][0] {    _id,    _type,    hero {      title,      subtitle,      ctaLabel,      "showreel": coalesce(showreelFile.asset->url, showreelUrl),      poster {   alt,  hotspot,  crop,  asset->{ _id, url, metadata { lqip, dimensions { width, height } } } }    },    about {      heading,      lead,      body,      stats[] { _key, value, label },      clients[] {        _key,        name,        logo { asset->{ _id, url, metadata { dimensions { width, height } } } }      }    },    portfolio {      title,      intro,      "cases": cases[]->{   _id,  title,  "slug": slug.current,  client,  category,  year,  orientation,  cover {   alt,  hotspot,  crop,  asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },  "fullVideo": coalesce(fullVideoFile.asset->url, fullVideoUrl),  "previewVideo": coalesce(previewVideoFile.asset->url, previewVideoUrl) }    },    faq {      title,      intro,      items[] { _key, question, answer }    },    contact { title, lede },    seo {      title,      description,      image { alt, asset->{ _id } }    }  }
export type HOME_QUERY_RESULT = {
  _id: "homePage";
  _type: "homePage";
  hero: {
    title: string | null;
    subtitle: string | null;
    ctaLabel: string | null;
    showreel: string | null;
    poster: {
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  about: {
    heading: string | null;
    lead: string | null;
    body: string | null;
    stats: Array<{
      _key: string;
      value: string | null;
      label: string | null;
    }> | null;
    clients: Array<{
      _key: string;
      name: string | null;
      logo: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
      } | null;
    }> | null;
  } | null;
  portfolio: {
    title: string | null;
    intro: string | null;
    cases: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      client: string | null;
      category: "commercial" | "short" | "youtube" | null;
      year: number | null;
      orientation: "horizontal" | "vertical" | null;
      cover: {
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
      } | null;
      fullVideo: string | null;
      previewVideo: string | null;
    }> | null;
  } | null;
  faq: {
    title: string | null;
    intro: string | null;
    items: Array<{
      _key: string;
      question: string | null;
      answer: string | null;
    }> | null;
  } | null;
  contact: {
    title: string | null;
    lede: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string | null;
      asset: {
        _id: string;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: CASES_QUERY
// Query: *[_type == "case" && defined(slug.current)] | order(coalesce(order, 999) asc, year desc) {      _id,  title,  "slug": slug.current,  client,  category,  year,  orientation,  cover {   alt,  hotspot,  crop,  asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },  "fullVideo": coalesce(fullVideoFile.asset->url, fullVideoUrl),  "previewVideo": coalesce(previewVideoFile.asset->url, previewVideoUrl)  }
export type CASES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  client: string | null;
  category: "commercial" | "short" | "youtube" | null;
  year: number | null;
  orientation: "horizontal" | "vertical" | null;
  cover: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  fullVideo: string | null;
  previewVideo: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: CASE_SLUGS_QUERY
// Query: *[_type == "case" && defined(slug.current)].slug.current
export type CASE_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../web/src/sanity/queries.ts
// Variable: CASE_QUERY
// Query: *[_type == "case" && slug.current == $slug][0] {      _id,  title,  "slug": slug.current,  client,  category,  year,  orientation,  cover {   alt,  hotspot,  crop,  asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },  "fullVideo": coalesce(fullVideoFile.asset->url, fullVideoUrl),  "previewVideo": coalesce(previewVideoFile.asset->url, previewVideoUrl),    scope,    summary,    gallery[] { _key, caption,   alt,  hotspot,  crop,  asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },    brief,    idea,    result,    credits[] { _key, role, name },    testimonial { quote, author, role }  }
export type CASE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  client: string | null;
  category: "commercial" | "short" | "youtube" | null;
  year: number | null;
  orientation: "horizontal" | "vertical" | null;
  cover: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  fullVideo: string | null;
  previewVideo: string | null;
  scope: Array<string> | null;
  summary: string | null;
  gallery: Array<{
    _key: string;
    caption: string | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  brief: string | null;
  idea: string | null;
  result: string | null;
  credits: Array<{
    _key: string;
    role: string | null;
    name: string | null;
  }> | null;
  testimonial: {
    quote: string | null;
    author: string | null;
    role: string | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: SITEMAP_QUERY
// Query: *[_type == "case" && defined(slug.current)] { "slug": slug.current, _updatedAt }
export type SITEMAP_QUERY_RESULT = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_id == "siteSettings" && _type == "siteSettings"][0] {\n    name,\n    legalName,\n    registeredName,\n    location,\n    email,\n    phone,\n    telegram,\n    instagram,\n    linkedin\n  }\n': SETTINGS_QUERY_RESULT;
    '\n  *[_id == "homePage" && _type == "homePage"][0] {\n    _id,\n    _type,\n    hero {\n      title,\n      subtitle,\n      ctaLabel,\n      "showreel": coalesce(showreelFile.asset->url, showreelUrl),\n      poster { \n  alt,\n  hotspot,\n  crop,\n  asset->{ _id, url, metadata { lqip, dimensions { width, height } } }\n }\n    },\n    about {\n      heading,\n      lead,\n      body,\n      stats[] { _key, value, label },\n      clients[] {\n        _key,\n        name,\n        logo { asset->{ _id, url, metadata { dimensions { width, height } } } }\n      }\n    },\n    portfolio {\n      title,\n      intro,\n      "cases": cases[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  client,\n  category,\n  year,\n  orientation,\n  cover { \n  alt,\n  hotspot,\n  crop,\n  asset->{ _id, url, metadata { lqip, dimensions { width, height } } }\n },\n  "fullVideo": coalesce(fullVideoFile.asset->url, fullVideoUrl),\n  "previewVideo": coalesce(previewVideoFile.asset->url, previewVideoUrl)\n }\n    },\n    faq {\n      title,\n      intro,\n      items[] { _key, question, answer }\n    },\n    contact { title, lede },\n    seo {\n      title,\n      description,\n      image { alt, asset->{ _id } }\n    }\n  }\n': HOME_QUERY_RESULT;
    '\n  *[_type == "case" && defined(slug.current)] | order(coalesce(order, 999) asc, year desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  client,\n  category,\n  year,\n  orientation,\n  cover { \n  alt,\n  hotspot,\n  crop,\n  asset->{ _id, url, metadata { lqip, dimensions { width, height } } }\n },\n  "fullVideo": coalesce(fullVideoFile.asset->url, fullVideoUrl),\n  "previewVideo": coalesce(previewVideoFile.asset->url, previewVideoUrl)\n\n  }\n': CASES_QUERY_RESULT;
    '\n  *[_type == "case" && defined(slug.current)].slug.current\n': CASE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "case" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  client,\n  category,\n  year,\n  orientation,\n  cover { \n  alt,\n  hotspot,\n  crop,\n  asset->{ _id, url, metadata { lqip, dimensions { width, height } } }\n },\n  "fullVideo": coalesce(fullVideoFile.asset->url, fullVideoUrl),\n  "previewVideo": coalesce(previewVideoFile.asset->url, previewVideoUrl)\n,\n    scope,\n    summary,\n    gallery[] { _key, caption, \n  alt,\n  hotspot,\n  crop,\n  asset->{ _id, url, metadata { lqip, dimensions { width, height } } }\n },\n    brief,\n    idea,\n    result,\n    credits[] { _key, role, name },\n    testimonial { quote, author, role }\n  }\n': CASE_QUERY_RESULT;
    '\n  *[_type == "case" && defined(slug.current)] { "slug": slug.current, _updatedAt }\n': SITEMAP_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
