/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Case = {
  _id: string;
  _type: "case";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  client?: string;
  category?: "commercial" | "youtube" | "short";
  year?: number;
  scope?: Array<string>;
  summary?: string;
  featured?: boolean;
  order?: number;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  fullVideoFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  fullVideoUrl?: string;
  previewVideoFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  previewVideoUrl?: string;
  orientation?: "horizontal" | "vertical";
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  brief?: string;
  idea?: string;
  result?: string;
  credits?: Array<{
    role?: string;
    name?: string;
    _type: "credit";
    _key: string;
  }>;
  testimonial?: {
    quote?: string;
    author?: string;
    role?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SanityFileAssetReference
  | Case
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: CASES_QUERY
// Query: *[_type == "case" && defined(slug.current)] | order(coalesce(order, 999) asc, year desc) {    _id,    title,    "slug": slug.current,    client,    category,    year,    featured,    orientation,    cover { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },    "fullVideo": coalesce(fullVideoFile.asset->url, fullVideoUrl),    "previewVideo": coalesce(previewVideoFile.asset->url, previewVideoUrl)  }
export type CASES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  client: string | null;
  category: "commercial" | "short" | "youtube" | null;
  year: number | null;
  featured: boolean | null;
  orientation: "horizontal" | "vertical" | null;
  cover: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  fullVideo: string | null;
  previewVideo: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: CASE_SLUGS_QUERY
// Query: *[_type == "case" && defined(slug.current)].slug.current
export type CASE_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../web/src/sanity/queries.ts
// Variable: CASE_QUERY
// Query: *[_type == "case" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    client,    category,    year,    scope,    summary,    orientation,    cover { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },    "fullVideo": coalesce(fullVideoFile.asset->url, fullVideoUrl),    "previewVideo": coalesce(previewVideoFile.asset->url, previewVideoUrl),    gallery[] { _key, alt, caption, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },    brief,    idea,    result,    credits[] { _key, role, name },    testimonial { quote, author, role }  }
export type CASE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  client: string | null;
  category: "commercial" | "short" | "youtube" | null;
  year: number | null;
  scope: Array<string> | null;
  summary: string | null;
  orientation: "horizontal" | "vertical" | null;
  cover: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  fullVideo: string | null;
  previewVideo: string | null;
  gallery: Array<{
    _key: string;
    alt: string | null;
    caption: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  brief: string | null;
  idea: string | null;
  result: string | null;
  credits: Array<{
    _key: string;
    role: string | null;
    name: string | null;
  }> | null;
  testimonial: {
    quote: string | null;
    author: string | null;
    role: string | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: SITEMAP_QUERY
// Query: *[_type == "case" && defined(slug.current)] { "slug": slug.current, _updatedAt }
export type SITEMAP_QUERY_RESULT = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "case" && defined(slug.current)] | order(coalesce(order, 999) asc, year desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    client,\n    category,\n    year,\n    featured,\n    orientation,\n    cover { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },\n    "fullVideo": coalesce(fullVideoFile.asset->url, fullVideoUrl),\n    "previewVideo": coalesce(previewVideoFile.asset->url, previewVideoUrl)\n  }\n': CASES_QUERY_RESULT;
    '\n  *[_type == "case" && defined(slug.current)].slug.current\n': CASE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "case" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    client,\n    category,\n    year,\n    scope,\n    summary,\n    orientation,\n    cover { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },\n    "fullVideo": coalesce(fullVideoFile.asset->url, fullVideoUrl),\n    "previewVideo": coalesce(previewVideoFile.asset->url, previewVideoUrl),\n    gallery[] { _key, alt, caption, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },\n    brief,\n    idea,\n    result,\n    credits[] { _key, role, name },\n    testimonial { quote, author, role }\n  }\n': CASE_QUERY_RESULT;
    '\n  *[_type == "case" && defined(slug.current)] { "slug": slug.current, _updatedAt }\n': SITEMAP_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
